version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myblog?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: myblog
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3307:3306" # Menggunakan port 3307 pada host untuk dihubungkan ke port 3306 pada container
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: