spring:
  datasource:
    url: jdbc:mysql://mysql:3306/myblog?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  profiles:
    active: # Uncomment this line if you want to activate a profile
    # - prod

logging:
  level:
    org.springframework.security: DEBUG

app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 86400